apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/dashboard-provider: {{ include (print $.Template.BasePath "/configmap-dashboard-provider.yaml") . | sha256sum }}
        checksum/dashboard-node-exporter: {{ include (print $.Template.BasePath "/configmap-node-exporter-dashboard.yaml") . | sha256sum }}
        checksum/dashboard-argocd: {{ include (print $.Template.BasePath "/configmap-dashboard-argocd.yaml") . | sha256sum }}
        checksum/dashboard-cluster-resources: {{ include (print $.Template.BasePath "/configmap-dashboard-cluster-resources.yaml") . | sha256sum }}
        checksum/dashboard-pod-resources: {{ include (print $.Template.BasePath "/configmap-dashboard-pod-resources.yaml") . | sha256sum }}
        checksum/dashboard-homelab-overview: {{ include (print $.Template.BasePath "/configmap-dashboard-homelab-overview.yaml") . | sha256sum }}
    spec:
      containers:
        - name: grafana
          image: "{{ .Values.image.repository }}@{{ .Values.image.digest }}"
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: admin
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: admin
          volumeMounts:
            - name: datasources
              mountPath: /etc/grafana/provisioning/datasources
            - name: dashboard-provider
              mountPath: /etc/grafana/provisioning/dashboards
            - name: dashboard-node-exporter
              mountPath: /etc/grafana/dashboards/node-exporter
            - name: dashboard-argocd
              mountPath: /etc/grafana/dashboards/argocd
            - name: dashboard-cluster-resources
              mountPath: /etc/grafana/dashboards/cluster-resources
            - name: dashboard-pod-resources
              mountPath: /etc/grafana/dashboards/pod-resources
            - name: dashboard-homelab-overview
              mountPath: /etc/grafana/dashboards/homelab-overview
            - name: data
              mountPath: /var/lib/grafana
      volumes:
        - name: datasources
          configMap:
            name: grafana-datasources
        - name: dashboard-provider
          configMap:
            name: grafana-dashboard-provider
        - name: dashboard-node-exporter
          configMap:
            name: grafana-dashboard-node-exporter
        - name: dashboard-argocd
          configMap:
            name: grafana-dashboard-argocd
        - name: dashboard-cluster-resources
          configMap:
            name: grafana-dashboard-cluster-resources
        - name: dashboard-pod-resources
          configMap:
            name: grafana-dashboard-pod-resources
        - name: dashboard-homelab-overview
          configMap:
            name: grafana-dashboard-homelab-overview
        - name: data
          persistentVolumeClaim:
            claimName: grafana-data
