apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-verify-script
  namespace: monitoring
  annotations:
    argocd.argoproj.io/hook: PostSync
data:
{{- (.Files.Glob "scripts/*").AsConfig | nindent 2 }}
